# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bookitnow
spring.data.mongodb.database=bookitnow

# JWT - change secret before production (use a long random string)
jwt.secret=ReplaceThisWithAStrongAndLongSecretKey_AtLeast_32_Chars
jwt.expiration-ms=86400000

# allow bean overriding (helpful while developing)
spring.main.allow-bean-definition-overriding=true
